rvm: 2.6

sudo: required
services: docker
cache: bundler

install: bundle install

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

dist: xenial
addons:
  apt:
    packages:
    - linux-headers-`uname -r`

script:
- ls -l /usr/src/
- bundle exec foodcritic config/cookbooks/raspberry
- cd config && bundle exec kitchen verify